# Generated by Django 4.0.2 on 2022-06-02 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserReg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='images/')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('dateofbirth', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'rent_user',
            },
        ),
        migrations.CreateModel(
            name='PostProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
                ('owner_name', models.CharField(max_length=20)),
                ('bed', models.IntegerField()),
                ('bath', models.IntegerField()),
                ('furnishing', models.CharField(max_length=20)),
                ('built_area', models.IntegerField()),
                ('carpet_area', models.IntegerField()),
                ('total_floor', models.IntegerField()),
                ('floor_no', models.BigIntegerField()),
                ('bachelors_allowed', models.CharField(max_length=5)),
                ('street', models.CharField(max_length=30)),
                ('district', models.CharField(max_length=30)),
                ('upload_images', models.ImageField(upload_to='images/')),
                ('price', models.IntegerField()),
                ('package', models.CharField(default='None', max_length=10)),
                ('contact_no', models.BigIntegerField()),
                ('status', models.BooleanField(default=False)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.userreg')),
            ],
            options={
                'db_table': 'property',
            },
        ),
    ]
