# Generated by Django 4.0.2 on 2022-06-02 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userreg',
            name='image',
        ),
        migrations.AddField(
            model_name='userreg',
            name='upload_image',
            field=models.ImageField(default=None, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='userreg',
            name='dateofbirth',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
