# Generated by Django 4.0.1 on 2022-05-09 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_userreg_confirm_pass'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userreg',
            table='rent_user',
        ),
    ]
