# Generated by Django 4.0.2 on 2022-06-02 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_userreg_image_userreg_upload_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreg',
            name='city',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='userreg',
            name='first_name',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='userreg',
            name='last_name',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='userreg',
            name='state',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
