# Generated by Django 4.0.2 on 2022-06-02 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_userreg_city_alter_userreg_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreg',
            name='city',
            field=models.CharField(default='city', max_length=20),
        ),
        migrations.AlterField(
            model_name='userreg',
            name='first_name',
            field=models.CharField(default='first name', max_length=20),
        ),
        migrations.AlterField(
            model_name='userreg',
            name='last_name',
            field=models.CharField(default='last_name', max_length=20),
        ),
        migrations.AlterField(
            model_name='userreg',
            name='state',
            field=models.CharField(default='state', max_length=20),
        ),
    ]
