# Generated by Django 4.0.2 on 2022-06-02 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_userreg_city_alter_userreg_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreg',
            name='dateofbirth',
            field=models.CharField(default='date of birth', max_length=100),
        ),
    ]
