# Generated by Django 4.0.1 on 2022-05-09 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_userreg_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreg',
            name='email',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='userreg',
            name='password',
            field=models.CharField(max_length=20),
        ),
    ]
