# Generated by Django 4.0.2 on 2022-06-02 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_userreg_dateofbirth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreg',
            name='city',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='userreg',
            name='dateofbirth',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='userreg',
            name='first_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='userreg',
            name='last_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='userreg',
            name='state',
            field=models.CharField(default='', max_length=20),
        ),
    ]
