# Generated by Django 4.0.1 on 2022-05-12 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_userreg_email_alter_userreg_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
                ('ower_name', models.CharField(max_length=20)),
                ('bed', models.IntegerField()),
                ('bath', models.IntegerField()),
                ('furnishing', models.CharField(max_length=20)),
                ('built_area', models.IntegerField()),
                ('carpet_area', models.IntegerField()),
                ('total_floor', models.IntegerField()),
                ('floor_no', models.BigIntegerField()),
                ('bachelors_allowed', models.CharField(max_length=5)),
                ('street', models.CharField(max_length=30)),
                ('district', models.CharField(max_length=30)),
                ('upload_images', models.ImageField(upload_to='images/')),
                ('price', models.IntegerField()),
                ('package', models.CharField(default='None', max_length=10)),
                ('contact_no', models.BigIntegerField()),
            ],
        ),
    ]
