# Generated by Django 4.0.2 on 2022-06-06 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_userreg_city_alter_userreg_dateofbirth_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postproperty',
            name='package',
        ),
        migrations.AddField(
            model_name='postproperty',
            name='premium_package',
            field=models.BooleanField(default=False),
        ),
    ]
