# Generated by Django 4.0.1 on 2022-05-12 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_postproperty'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='postproperty',
            table='property',
        ),
    ]
