# Generated by Django 4.0.1 on 2022-05-14 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_postproperty_owner_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='postproperty',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.userreg'),
        ),
    ]
