# Generated by Django 4.0.1 on 2022-05-14 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_postproperty_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postproperty',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.userreg'),
        ),
    ]
