# Generated by Django 4.0.2 on 2022-06-10 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_favourites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postproperty',
            name='bachelors_allowed',
            field=models.CharField(default='', max_length=5),
        ),
    ]
