# Generated by Django 4.0.1 on 2022-05-23 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_postproperty_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='postproperty',
            name='status',
            field=models.CharField(default='pending', max_length=10),
        ),
    ]
