# Generated by Django 4.0.1 on 2022-05-23 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_postproperty_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postproperty',
            name='status',
            field=models.CharField(default='', max_length=10),
        ),
    ]
